variables:
  - &ci_image 'cont-reg.bjodah.se:443/bjodah/triceratops-5:25'

when:
  - event: [push]

steps:
  - name: run-test-suite
    image: *ci_image
    commands:
      - bash -lc "./scripts/build-and-test.sh"
      - bash -lc "./scripts/run-lint-checks.sh"
